[CMLG-015] Refactor the code
UoaWDCC/WDCC_COVID-19_Multilingual_Glossary_Frontend pull request #63
Opened 2020-11-02 13:27 UTC by ywu666

Issue: 
Try to make the files structure become more clear.

Solution: 
Moving files into the corresponding package.

Risk: --

Reviewed By:
Emily, Eileen, Kevin, Annie, Dave

2020-11-12 01:40 UTC, zyan225 requested changes
Are the changes for SelectCol already in master? (i can't remember so just double checking here). Maybe merged in after Annie finishes her CSS styling.

2020-11-12 02:04 UTC, ywu666 commented
Yes, I just refactor. Didn't change the functionality. Cause there is some duplicate code.

2020-11-12 21:04 UTC, hiin3d55 approved these changes

2020-11-24 10:24 UTC, EileenSiqi approved these changes

2020-11-25 08:01 UTC, zyan225 approved these changes
Nice job!

2020-11-25 08:24 UTC, merged