[CMLG-035] Dark Mode Start Button
UoaWDCC/WDCC_COVID-19_Multilingual_Glossary_Frontend pull request #79
Opened 2021-05-20 02:02 UTC by minssunkim

Issue :
On dark mode, when you hover over the button, the colours are not inverted.
We want a white background with black text but we previously had a grey background with white text.

Solution :
Added .btn-dark-mode:hover in WelcomPage.css to invert the colours when you hover over it.

Risk :
Button colour could be incorrect

Reviewed by :
Dave, Annie, Kevin, Eileen, Hayoon, Clarissa

2021-05-27 01:33 UTC, jge385 requested changes
Good job!  a small thing is that  could u delete the HelloWorld file?    Others are awesome :)

2021-06-03 02:21 UTC, hiin3d55 approved these changes

2021-06-03 02:26 UTC, annithinggoes approved these changes
Yea maybe use just use the predefined "white" and "black" for the colour selction in the future? but otherwise looks good

2021-06-03 02:31 UTC, EileenSiqi approved these changes

2021-06-05 05:15 UTC, jge385 approved these changes
Good job!~

2021-07-22 05:32 UTC, merged